# Generated by Django 5.0.2 on 2024-03-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
