# Generated by Django 5.0.2 on 2024-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0003_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
