# Generated by Django 5.0.2 on 2024-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0005_bankbalance_count_expense_extraexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbalance',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='count',
            name='notes_100',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='count',
            name='notes_200',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='count',
            name='notes_500',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='count',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='extraexpense',
            name='notes_100',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extraexpense',
            name='notes_200',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extraexpense',
            name='notes_500',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extraexpense',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
