# Generated by Django 5.0.2 on 2024-04-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0006_alter_bankbalance_time_alter_count_notes_100_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('no_of_expense', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.RemoveField(
            model_name='count',
            name='total',
        ),
        migrations.RemoveField(
            model_name='extraexpense',
            name='total',
        ),
    ]
