# Generated by Django 5.0.2 on 2024-04-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0007_child_expense_parent_expense_delete_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbalance',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='count',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='extraexpense',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parent_expense',
            name='time',
            field=models.DateField(),
        ),
    ]
