# Generated by Django 5.0.2 on 2024-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0009_alter_count_notes_100_alter_count_notes_200_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='total_sales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
