# Generated by Django 5.0.2 on 2024-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0011_extraexpense_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_Expense_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='extraexpense',
            name='no_of_expense',
            field=models.IntegerField(default=0),
        ),
    ]
