# Generated by Django 5.0.2 on 2024-05-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hisab', '0012_extra_expense_details_extraexpense_no_of_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraexpense',
            name='description',
        ),
    ]
